language: php
php:
  - 5.6
  - 7.0
  - 7.4

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev

script:
  - phpunit

matrix:
  allow_failures:
    - php: hhvm
